apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-block
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes: [ReadWriteOnce]
  volumeMode: Block
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
