{{- if .Values.security.sccBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sample.name" . }}-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
  {{- with .Values.resourceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [security.openshift.io]
    resources: [securitycontextconstraints]
    resourceNames: [{{ .Values.security.sccBinding.name | quote }}]
    verbs: [use]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sample.name" . }}-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
  {{- with .Values.resourceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sample.account" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sample.name" . }}-scc
{{- end }}
