apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- (.Files.Glob "scripts/*.sh").AsConfig | nindent 2 }}
